server.host=0.0.0.0
spring.datasource.url=jdbc:mysql://localhost:3306/school_erp
spring.datasource.username=root
spring.datasource.password=Ananya0702@0601@12

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.ssl.enabled=true
server.ssl.key-store=classpath:localhost+3.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12

test.url=https://172.16.139.45:8080