server.host=0.0.0.0
spring.datasource.url=jdbc:mysql://172.30.112.1:3306/college_erp
spring.datasource.username=schooluser
spring.datasource.password=schoolpassword

spring.data.redis.host=172.30.112.1
spring.data.redis.port=6379

#server.ssl.enabled=true
#server.ssl.key-store=classpath:localhost+3.p12
#server.ssl.key-store-password=changeit
#server.ssl.key-store-type=PKCS12

test.url=http://172.30.112.1:8080